version: "3.7"
services:
  postgres:
    image: postgres:13-alpine
    environment:
      POSTGRES_PASSWORD: pass
      POSTGRES_USER: postgres
      POSTGRES_DB: rss-reader
    ports:
      - 5432:5432

  adminer:
    image: adminer
    ports:
      - 8080:8080
    depends_on: 
      - postgres

  rss-reader-init:
    build:
      context: ./
      dockerfile: ./docker/init/Dockerfile
    depends_on:
      - postgres