// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package internal

// Injectors from wire.go:

// BuildAggregator
func BuildAggregator(cfg *Config) (*Aggregator, func(), error) {
	v := GetFeedConfigs(cfg)
	loader := NewLoader(v)
	parser := NewParser()
	dbConfig := GetDBConfig(cfg)
	conn, cleanup, err := NewPGXConn(dbConfig)
	if err != nil {
		return nil, nil, err
	}
	postRepository := NewPostRepository(conn)
	pgMutex, err := NewPGMutex(conn)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	aggregator := NewAggregator(loader, parser, postRepository, pgMutex)
	return aggregator, func() {
		cleanup()
	}, nil
}

// BuildRepository
func BuildRepository(cfg *Config) (*PostRepository, func(), error) {
	dbConfig := GetDBConfig(cfg)
	conn, cleanup, err := NewPGXConn(dbConfig)
	if err != nil {
		return nil, nil, err
	}
	postRepository := NewPostRepository(conn)
	return postRepository, func() {
		cleanup()
	}, nil
}
